var backgroundset = {
                        "Setti 1":["Fly me to the moon",
                        "Bye Bye Blackbird",
                        "C'est si bon",
                        "Cavatina",
                        "Petite Fleur",
                        "Kissa vieköön",
                        "Viimeinen ilta",
                        "Kuolleet lehdet",
                        "How insensitive",
                        "Lady be good",
                        "Misty",
                        "Georgia on my mind"],

                        "Setti 2":["Tea for two",
                        "The midnight sun will never set",
                        "Kuutamoserenadi",
                        "Caravan",
                        "Smoke gets in your eyes",
                        "Rebekka",
                        "Rakkauden Satu",
                        "Se jääköön huomiseen",
                        "Ranskalaiset korot",
                        "The girl from Ipanema",
                        "The days of wine and roses",
                        "Vippaa mulle viitonen"
                        ],

                        "Setti 3":["Akselin ja Elinan häävalssi",
                        "Nuoruusmuistoja",
                        "Hopeinen Kuu",
                        "Paranoid",
                        "Jätkän humppa",
                        "Satumaa",
                        "Sä kaunehin oot",
                        "Kultainen nuoruus ",
                        "Tango Sinikalle",
                        "Suvivalssi",
                        "Minä rakastan sua"
                        ]}