var danceset = {
                "Setti 1":[
                "Åsele valssi / Metsäkukkia",
                "Hanurin kutsu",
                "Orpo",
                "Siperia",
                "Uno",
                "Palaa, luokseni",
                "Moksis / Lookia",
                "When I'm 64 ",
                "Teetä kahdelle / Rebekka",
                "Ystävänpäivä / Sway",
                "Roteva ja romanttinen",
                "Sukuvika",
                "JänkäJenkka"],

                "Setti 2": ["Sininen huivi",
                "Metsäpirtti / Turun surusilmä",
                "TV:n kokoinen haitari",
                "Merimies",
                "Rakkaus on sininen",
                "Aamu",
                "Paratiisi",
                "Mahdunko maailmaas",
                "Lapin tango",
                "Kesäinen muisto / Punaiset lehdet",
                "Paha vaanii",
                "Kohti Valoa",
                "Lukkari Heikin polkka",
                "Karjalan poikia",],
                
                "Setti 3":["St Pauli ja Reeperbahn",
                "Eviva Espanja",
                "Besame Mucho",
                "Kuihtuu kesäinen maa",
                "Sitä saa mitä tilaa",
                "Kaksin rannalla yksinäiset",
                "Feisbuugie",
                "Teryleeniä",
                "Kesäillan valssi / Kyrösjärven laineilla",
                "Mantsurian kukkuloilla",
                "Saharan lilja",
                "Kangastusta",
                "Aamuyön ikuisuus",
                "Kaksi puuta",
                "Marilyn",
                "Juankoski here I come",],

                "Setti 4":["The Midnight Sun will never set",
                "On hetki",
                "On lautalla pienoinen kahvila",
                "Bulu bulu bulu",
                "Vie meidät rakkauteen",
                "Yön kuningatar",
                "Taas on aika auringon",
                "Saarenmaan valssi",
                "Olet mun sä vain",
                "Let it be me",
                "Metsämökin tonttu",
                "Friduna Skiguna",
                "Mä jäin kii ",
                "Juhlimaan",
                "Rock around the clock",
                "Blue Suede Shoes",],

                "Setti 5":["Are you lonesome tonight",
                "Charade",
                "Oot täydellinen",
                "Hyvännäköinen",
                "Kaikkea hyvää",
                "Hiljainen on laulu rakkauden",
                "Kesäilta Saimaalla",
                "Takaisinpaluu",
                "Tango Pelargonia",
                "Soita mulle kitarain",
                "Soita Humupekka",
                "Souvaripoikia",
                "Tallinnan illat",
                "Pohjolan yö",],

                "Setti 6":["Saanhan viimeisen tanssin",
                "Väliaikainen / Rakkauden Satu",
                "15 kesää",
                "15:sta yö",
                "Lähdön hetkellä",
                "Tuuli tuo tuuli vie",
                "Just a Gigolo",
                "Tuollainen tyttö",
                "Muruseni",
                "Aikuinen nainen",
                "Rantakoivun alla (Dm)",
                "Yölintu",
                "Lentävä kalakukko",
                "Kulkurin masurkka"
                ],

                "Setti 7":["Kulkurin kaiho",
                "Kalastaja Eemelin valssi",
                "Tiikerihai",
                "Pihapihlaja",
                "Asuncion",
                "Guapita",
                "Kissa vieköön",
                "Bye bye blackbird",
                "Amor Amor",
                "Caravan",
                "Letkis",
                "Puhelinlangat laulaa",
                "Häävalssi elokuvasta Kummisetä",
                "Käyn uudelleen eiliseen"
                ],

                "Setti 8":["Tammerkoski",
                "Yö Altailla",
                "Suhmuran Santra",
                "Kerran saavun satamaan",
                "Eva",
                "Sulamith",
                "Yö ikkunan takana",
                "Yön tummat siivet",
                "All of me",
                "Muista minua",
                "Päivin öin",
                "Kaksi ruusua",
                "Vesivehmaan jenkka",
                "Rempallaan"]}