var popsets = {
                "Setti 1":["All my loving",
                "Eight days a week",
                "I saw her standing there",
                "Ja rokki soi",
                "That's allright mama",
                "Mun sormuksein",
                "Saat miehen kyyneliin",
                "Always on my mind",
                "Jos jotain yrittää",
                "Äidin pikkupoika",
                "La Bamba",
                "Vielä on kesää jäljellä",
                "Tsingis Khan ",
                "Titanic"
                ],
                
                "Setti 2":["Rasputin",
                "Volga",
                "Daa da daa",
                "R A K A S",
                "Dirlandaa",
                "Syntymäpäivä (SIG)",
                "Mä putoan",
                "Syksyn sävel",
                "Muisto vain jää",
                "Elämältä kaiken sain",
                "Juodaan viinaa",
                "Ei tippa tapa",
                "Viimeinkin",
                "Vanhoja poikia viiksekkäitä"
                ],

                "Setti 3":["Rappiolla",
                "Bourbon Street",
                "Hän",
                "Salattu suru",
                "Lauantai-ilta",
                "I only wanna be with you",
                "Cadillac",
                "Walkin' the dog",
                "Kauppaopiston naiset",
                "Ajetaan tandemilla",
                "Tykkään susta niin että halkeen",
                "Kaunis nainen"],
                
                "Setti 4":["And I love her",
                "Michelle",
                "Girl",
                "In my life",
                "Eleanor Rigby",
                "Here, there and everywhere",
                "She's leaving home",
                "Yesterday",
                "When I'am 64",
                "Strawberry fields 4 ever",
                "Hey Jude",
                "Because",
                "Something",
                "The long and winding road",
                "Let it be",
                "Till there was you",
                "Honey Pie"
                ],

                "Setti 5":["Sirpa",
                "Rentun ruusu",
                "Live is life",
                "Poing poing",
                "Oikeesti",
                "Onni on matka",
                "Mitä silmät ei nää",
                "Kultaniityt",
                "Valot",
                "Can't help falling in love",
                "Salainen rakkaus",
                "Tähdet tähdet",
                "Guantanamera",
                "Jos sä tahdot "
                ]
    }